# Generated by Django 2.2.1 on 2019-05-11 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('deadline', models.DateTimeField()),
                ('progress', models.CharField(max_length=4)),
            ],
        ),
    ]
